# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspot',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
